[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "www_Day_Dream"
name = "CessilCellsCeaChells"
description = "Allows installed plugins to request creation of Fields, Properties, Methods, and more in Managed DLLs."
websiteUrl = "https://github.com/wwwDayDream/CessilCellsCeaChells"
containsNsfwContent = false

[build]
icon = "icon.png"
readme = "README.md"
outdir = "../dist"

[[build.copy]]
source = "../LICENSE"
target = "/"

[[build.copy]]
source = "../CessilCellsCeaChells.Preloader/bin/Mono10/net35/CessilCellsCeaChells.dll"
target = "/BepInEx/patchers/CessilCellsCeaChells/"

[[build.copy]]
source = "../CessilCellsCeaChells.Preloader/bin/Mono10/net35/CessilCellsCeaChells.Preloader.dll"
target = "/BepInEx/patchers/CessilCellsCeaChells/"

[publish]
communities = [ "content-warning", "lethal-company", "riskofrain2", "dyson-sphere-program" ]
categories = [ "libraries" ]