[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "www_Day_Dream"
name = "CessilCellsCeaChells"
description = "Allows installed plugins to request creation of Fields, Properties, and Methods in Managed DLLs."
websiteUrl = "https://github.com/wwwDayDream/CessilCellsCeaChells"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "icon.png"
readme = "README.md"
outdir = "../dist"

[[build.copy]]
source = "../../LICENSE"
target = "/"

[[build.copy]]
source = "../bin/Release/netstandard2.1/CessilCellsCeaChells.dll"
target = "/BepInEx/patchers/CessilCellsCeaChells/"

[publish]
communities = [ "content-warning" ]
[publish.categories]
content-warning = [ "libraries" ]
# For a list of valid tags, look at the slug values in https://thunderstore.io/api/experimental/community/content-warning/category/
