name: Build

on:
  push:
    branches: [ test ]
  pull_request:

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@{latest-release}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  build:
    name: Build
    needs: changelog
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup .NET Env
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.203"

      - name: Run Cake Build Script
        run: |
          dotnet run --project build/Build.csproj --target Build

      - name: Upload Thunderstore Artifact
        uses: actions/upload-artifact@v4
        with:
          name: thunderstore-build
          path: dist/*.zip

      - name: Upload CessilCellsCeaChells NuPkg Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cccc-nupkg
          path: dist/cessil/*.nupkg

      - name: Upload CessilCellsCeaChells.Cli Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cli-build
          path: dist/cli/*.zip

      - name: Upload CessilCellsCeaChells.MSBuild NuPkg Artifact
        uses: actions/upload-artifact@v4
        with:
          name: msbuild-nupkg
          path: dist/msbuild/*.nupkg
